[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npm run build",
  "cp -r .next/static .next/standalone/.next/",
  "cp -r public .next/standalone/"
]

[start]
cmd = "cd .next/standalone && node server.js"
